sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  fast_finish: true
  include:
    - php: '5.6'
      env:
        - DEV="--no-dev"
    - php: '5.6'
      env:
        - TESTS=1
    - php: '7.0'
      env:
        - DEV="--no-dev"
    - php: '7.0'
      env:
        - TESTS=1
    - php: '7.1'
      env:
        - DEV="--no-dev"
    - php: '7.1'
      env:
        - TESTS=1
    - php: '7.2'
      env:
        - DEV="--no-dev"
    - php: '7.2'
      env:
        - TESTS=1
    - php: '7.3'
      env:
        - DEV="--no-dev"
    - php: '7.3'
      env:
        - TESTS=1
    - php: '7.4'
      env:
        - DEV="--no-dev"
    - php: '7.4'
      env:
        - SNIFF=1 TESTS=1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

before_script:
  - echo $COMPOSER_AUTH
  - phpenv rehash
  - composer install $DEV

script:
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs --colors; fi
  - if [[ "$TESTS" == "1" ]]; then make update-phpunit; fi
  - if [[ "$TESTS" == "1" ]]; then vendor/phpunit/phpunit/phpunit --configuration tests/phpunit/phpunit.xml; fi
